"""migration

Revision ID: 43ca933600ac
Revises: 0003_finished_flag
Create Date: 2025-08-09 18:43:45.453037
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43ca933600ac'
down_revision = '0003_finished_flag'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_players', sa.Column('score', sa.Integer(), nullable=False))
    op.add_column('games', sa.Column('started', sa.Boolean(), nullable=False))
    op.add_column('games', sa.Column('next_player_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('passes_in_a_row', sa.Integer(), nullable=False))
    op.add_column('games', sa.Column('phase', sa.String(), nullable=False))
    op.alter_column('games', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('games', 'phase')
    op.drop_column('games', 'passes_in_a_row')
    op.drop_column('games', 'next_player_id')
    op.drop_column('games', 'started')
    op.drop_column('game_players', 'score')
    # ### end Alembic commands ###
