"""migration

Revision ID: f249aee58340
Revises: ba2e98a9b8fc
Create Date: 2025-08-13 16:49:40.607327
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f249aee58340'
down_revision = 'ba2e98a9b8fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deletion_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('grace_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('privacy_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('game_players', sa.Column('display_name', sa.String(), nullable=True))
    op.drop_constraint(op.f('game_players_user_id_fkey'), 'game_players', type_='foreignkey')
    op.create_foreign_key(None, 'game_players', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deletion_locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deletion_locked_until')
    op.drop_column('users', 'deleted_at')
    op.drop_constraint(None, 'game_players', type_='foreignkey')
    op.create_foreign_key(op.f('game_players_user_id_fkey'), 'game_players', 'users', ['user_id'], ['id'])
    op.drop_column('game_players', 'display_name')
    op.drop_table('privacy_audit_log')
    op.drop_table('deletion_requests')
    # ### end Alembic commands ###
